spring:
  application:
   name: manage-service  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.54:8080/auth/realms/MSA/protocol/openid-connect/certs

# 유레카 클라이언트 설정
eureka:
  instance:
    instance-id: manage-microservice-instance # eureka에 등록되는 id 값
  client:
    register-with-eureka: true  # 유레카에 등록할지 여부.
    fetch-registry: true  # 유레카에서 조회할지 여부
    service-url:
      defaultZone: http://localhost:8761/eureka   # 서비스를 등록할 서버 주소를 지정
