spring:
  application:
    name: status-service
 devtools:
    livereload:
       enabled: true
    restart:
       enabled: true
  freemarker:
     cache: false
  thymeleaf:
     cache: false
  resources:
    static-locations: classpath:/resources/static/**
keycloak:
  realm: MSA
  bearer-only: true
  ssl-required: external
  resource: spring-gateway-client
  auth-server-url: http://192.168.1.54:8080/auth
  credentials:
    secret: WEcACPUTWPfuhPrEz3bBaHcl7OLLmYX1
